# Configuration file for Bitcoin Trust Prediction Project
# COMMUNITY DETECTION EPINIONS EXPERIMENT

# Dataset Configuration
data_path: data/soc-sign-epinions.txt

# Experiment naming
default_experiment_name: experiment_epinions_community

# Cross-validation settings
default_n_folds: 5

# Data splitting settings
num_test_edges: 4000
num_validation_edges: 2500

# Feature extraction settings
cycle_length: 4

# Model training settings
default_threshold: 0.5

# Validation settings
nr_val_predictions: 600
pos_edges_ratio: 0.5

# Testing settings
threshold_type: best_accuracy_threshold
n_test_predictions: 800
pos_test_edges_ratio: 0.5

# Task 1: Weighted Features Configuration
use_weighted_features: false
weight_method: sign
weight_bins: 5
preserve_original_weights: true
weight_aggregation: product

# Task 2: Bidirectional Edge Handling
bidirectional_method: max

# Community Detection Subset Sampling Configuration
enable_subset_sampling: true
subset_sampling_method: community_detection
target_edge_count: 40000
subset_preserve_structure: true

# Optional settings
memory_optimized: true
parallel_processing: true