# Configuration file for Bitcoin Trust Prediction Project
# UPDATED WITH OPTIMAL 74:12:14 SPLIT RATIO

# Dataset Configuration
data_path: data/soc-sign-epinions-best-balance.txt

# Experiment naming
default_experiment_name: experiment_epinions_optimal_balance

# Cross-validation settings
default_n_folds: 5

# Feature extraction settings
cycle_length: 4

# UPDATED: Data splitting settings using optimal 74:12:14 ratio
# Target: Test=3080, Validation=2640, remaining for training
num_test_edges: 3080          # Fixed: Optimal test set size
num_validation_edges: 2640    # Fixed: Optimal validation set size

# Model training settings
default_threshold: 0.5

# Training settings (ENABLE filtering feature)
min_train_embeddedness: 1
pos_train_edges_ratio: 0.8  # ACTIVATE: 80% positive as in original Epinions

# Validation settings (ENABLE filtering feature)
nr_val_predictions: 200     # Match requirements: 200
min_val_embeddedness: 1
pos_edges_ratio: 0.8       # ACTIVATE: 80% positive for balanced validation

# Testing settings (ENABLE filtering feature)
threshold_type: best_accuracy_threshold
n_test_predictions: 300     # Match requirements: 300
min_test_embeddedness: 1
pos_test_edges_ratio: 0.8   # ACTIVATE: 80% positive for balanced testing

# Task 1: Weighted Features Configuration
use_weighted_features: false  # Match requirements: unweighted for fair comparison
weight_method: raw
weight_bins: 5
preserve_original_weights: true

# Task 2: Bidirectional Edge Handling
bidirectional_method: max

# BFS SAMPLING CONFIGURATION
# Apply BFS sampling to get Epinions subset same size as Bitcoin OTC
enable_subset_sampling: true
subset_sampling_method: bfs_sampling  # Use suggested BFS approach
target_edge_count: 35000    # Same scale as Bitcoin OTC full dataset
subset_preserve_structure: true

# BFS-specific settings
bfs_seed_selection: random_moderate_degree  # Not highest degree as advised
bfs_degree_percentile: 70  # Select seed from moderate degree nodes

# OPTIMAL SPLIT RATIO CONFIGURATION
# These parameters define the 74:12:14 split ratio
split_ratio:
  train: 0.74    # 74% for training
  validation: 0.12  # 12% for validation (2640 samples)
  test: 0.14     # 14% for testing (3080 samples)

# Optional settings
memory_optimized: true
parallel_processing: true