bidirectional_method: max
data_path: data/soc-sign-bitcoinotc.csv
experiment_name: experiment_binary_optimized
n_folds: 5
num_test_edges: 4000
num_validation_edges: 4000
preserve_original_weights: true
use_weighted_features: false
weight_bins: 5
weight_method: sign
